steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genz-video-app-${_ENVIRONMENT}:$COMMIT_SHA', './server']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genz-video-app-${_ENVIRONMENT}:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genz-video-app-${_ENVIRONMENT}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genz-video-app-${_ENVIRONMENT}:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _ENVIRONMENT: dev  # default value

images:
  - 'gcr.io/$PROJECT_ID/genz-video-app-${_ENVIRONMENT}:$COMMIT_SHA'

timeout: 1800s
