// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLkaaslwRrvwr5W2p2-sEpoPx1TRHdRZI',
    appId: '1:56249782826:web:d4a70d544ad8e2abc92953',
    messagingSenderId: '56249782826',
    projectId: 'project-pod-dev',
    authDomain: 'project-pod-dev.firebaseapp.com',
    storageBucket: 'project-pod-dev.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ygIc0ig04ZmvJC6Z8RNwRrVl2V8Z2SQ',
    appId: '1:56249782826:android:3e0208545602fb7ac92953',
    messagingSenderId: '56249782826',
    projectId: 'project-pod-dev',
    storageBucket: 'project-pod-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJDIh27iKa5gjBiltKWRBbx2rj5GYY6sA',
    appId: '1:56249782826:ios:fcada8bb957fd1f8c92953',
    messagingSenderId: '56249782826',
    projectId: 'project-pod-dev',
    storageBucket: 'project-pod-dev.firebasestorage.app',
    iosBundleId: 'com.podwatch.app',
  );
}
